# Generated by Django 5.2.4 on 2025-08-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_auto_20250801_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modversion',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
