# Generated by Django 5.2.4 on 2025-08-01 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0003_alter_modversion_platform'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mod',
            unique_together={('name',)},
        ),
        migrations.AlterField(
            model_name='mod',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mods', to='mods.modcategory'),
        ),
    ]
