# Generated by Django 5.2.4 on 2025-08-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0004_alter_mod_unique_together_alter_mod_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modversion',
            name='minecraft_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
