# Generated by Django 5.2.4 on 2025-08-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0005_alter_modversion_minecraft_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='logo',
            field=models.TextField(blank=True),
        ),
    ]
