# Generated by Django 5.2.4 on 2025-08-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0006_mod_logo'),
    ]

    operations = [
    ]
