# Generated by Django 5.2.4 on 2025-08-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0007_auto_20250801_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mod',
            name='relevance_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
