# Generated by Django 5.2.4 on 2025-08-01 10:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0008_mod_download_count_mod_relevance_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_views', to='mods.mod')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('mod', 'ip_address')},
            },
        ),
    ]
