# Generated by Django 6.0.2 on 2026-05-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0010_alter_modview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='archive_url',
            field=models.URLField(blank=True, help_text="Link to the mod's page on archive.org"),
        ),
        migrations.AddField(
            model_name='mod',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
